name: Release

on:
  push:
    tags:
      - 'v*' # e.g. v1.2.3

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install freetypew
      run: sudo apt-get install libfreetype6-dev
    - name: Build on Linux
      run: |
        cargo build --verbose --release
        mv target/release/elisa target/release/elisa-linux
    - name: Archive Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-linux
        path: target/release/elisa-linux

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build on Windows
      run: |
        cargo build --verbose --release
        mv target/release/elisa.exe target/release/elisa-windows.exe
    - name: Archive Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-windows
        path: target/release/elisa-windows.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build on MacOS
      run: |
        cargo build --verbose --release
        mv target/release/elisa target/release/elisa-macos
    - name: Archive MacOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-macos
        path: target/release/elisa-macos

  release:
    # This job runs only after both build jobs successfully complete
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    permissions:
      contents: write # write permissions are required to create a release
    steps:
      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-linux
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-windows
      - name: Download MacOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-macos
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          # The tag name (e.g., v1.0.0) is automatically used as the release name/tag
          files: |
            elisa-linux
            elisa-macos
            elisa-windows.exe
        env:
          # GITHUB_TOKEN is a secret provided by GitHub automatically
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
